MvcCodeFlowClientManual/Controllers/AppController.cs
using Intuit.Ipp.OAuth2PlatformClient;
using System;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using System.Net;
using Intuit.Ipp.Core;
using Intuit.Ipp.Data;
using Intuit.Ipp.QueryFilter;
using Intuit.Ipp.Security;
using System.Linq;
using System.Collections.Generic;
using MvcCodeFlowClientManual.Model;
using System.Web.UI.WebControls;
using System.Globalization;
using MvcCodeFlowClientManual.Migrations;
using Category = MvcCodeFlowClientManual.Model.Category;

namespace MvcCodeFlowClientManual.Controllers
{
    [Route("App/AppController")]
    public class AppController : Controller
    {
        public static string clientid = ConfigurationManager.AppSettings["clientid"];
        public static string clientsecret = ConfigurationManager.AppSettings["clientsecret"];
        public static string redirectUrl = ConfigurationManager.AppSettings["redirectUrl"];
        public static string environment = ConfigurationManager.AppSettings["appEnvironment"];

        public static OAuth2Client auth2Client = new OAuth2Client(clientid, clientsecret, redirectUrl, environment);
        private DbEntity _db = new DbEntity();

        /// <summary>
        /// Use the Index page of App controller to get all endpoints from discovery url
        /// </summary>
        public ActionResult Index()
        {
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
            Session.Clear();
            Session.Abandon();
            Request.GetOwinContext().Authentication.SignOut("Cookies");
            return View();
        }

        /// <summary>
        /// Start Auth flow
        /// </summary>
        public ActionResult InitiateAuth(string submitButton)
        {
            switch (submitButton)
            {
                case "Connect to QuickBooks":
                    List<OidcScopes> scopes = new List<OidcScopes>();
                    scopes.Add(OidcScopes.Accounting);
                    string authorizeUrl = auth2Client.GetAuthorizationURL(scopes);
                    return Redirect(authorizeUrl);
                default:
                    return (View());
            }
        }

        /// <summary>
        /// QBO API Request
        /// </summary>
        public ActionResult ApiCallService()
        {
            ProjectData vm = new ProjectData();
            List<Customer> listProject = new List<Customer>();
            if (Session["realmId"] != null)
            {
                string realmId = Session["realmId"].ToString();
                try
                {
                    var principal = User as ClaimsPrincipal;
                    OAuth2RequestValidator oauthValidator = new OAuth2RequestValidator(principal.FindFirst("access_token").Value);

                    // Create a ServiceContext with Auth tokens and realmId
                    ServiceContext serviceContext = new ServiceContext(realmId, IntuitServicesType.QBO, oauthValidator);
                    serviceContext.IppConfiguration.MinorVersion.Qbo = "65";

                    // Create a QuickBooks QueryService using ServiceContext
                    QueryService<Customer> querySvc = new QueryService<Customer>(serviceContext);
                    System.Collections.ObjectModel.ReadOnlyCollection<Customer> customerList = querySvc.ExecuteIdsQuery("SELECT * FROM Customer");

                    foreach (var item in customerList)
                    {
                        if (item.IsProject){
                            listProject.Add(item);
                        }
                    }

                    vm.Project = listProject;
                    vm.Message = "QBO API call Successful!!";
                    return View("ApiCallService", vm);
                }
                catch (Exception ex)
                {
                    vm.Project = listProject;
                    vm.Message = "QBO API call Failed!" + " Error message: " + ex.Message;
                    return View("ApiCallService", vm);
                }
            }
            else {
                vm.Project = listProject;
                vm.Message = "QBO API call Failed!";
                return View("ApiCallService", vm);
            }
        }

        public ActionResult GetSelectedProjectId(FormCollection fc) 
        {
            return RedirectToAction("Dashboard/" + fc["project"]);
        }

        [HttpGet]
        public ActionResult Dashboard(int id)
        {
            string projectId = id.ToString();
            SingleProjectData vm = new SingleProjectData();
            List<Bill> listBill = new List<Bill>();

            if (Session["realmId"] != null)
            {
                string realmId = Session["realmId"].ToString();
                try
                {
                    var dashBoardData = (from c in _db.Contrats
                            join d in _db.Depenses on c.Contract_Id equals d.Contract_Id into ps
                            where c.Project_Id == id
                            from d in ps.DefaultIfEmpty()
                            join cat in _db.Categorys on d.Category_Id equals cat.CategoryId into us
                            from cat in us.DefaultIfEmpty()
                            select new ProjectInformation { Contract_Id = c.Contract_Id,
                                                            ContractAmount = c.Amount,
                                                            DepenseAmount = d == null ? 0 : d.Amount,
                                                            CategoryName = cat.Name == null ? "Aucune" : cat.Name}).ToList();
                    var allContract = (from c in _db.Contrats
                                         where c.Project_Id == id
                                         select new ContratInformation
                                         {
                                             Contract_Id = c.Contract_Id,
                                             ContractAmount = c.Amount,
                                         }).ToList();
                    var dataBudget = (from s in _db.Budgets where s.Project_Id == id select s.Amount == null ? 0 : s.Amount).FirstOrDefault();

                    var listContrat = (from s in _db.Contrats select s).ToList();

                
                        var principal = User as ClaimsPrincipal;
                        OAuth2RequestValidator oauthValidator = new OAuth2RequestValidator(principal.FindFirst("access_token").Value);

                        // Create a ServiceContext with Auth tokens and realmId
                        ServiceContext serviceContext = new ServiceContext(realmId, IntuitServicesType.QBO, oauthValidator);
                        serviceContext.IppConfiguration.MinorVersion.Qbo = "65";

                        QueryService<Customer> querySvc = new QueryService<Customer>(serviceContext);
                        QueryService<Invoice> querySvcInvoice = new QueryService<Invoice>(serviceContext);
                        QueryService<Bill> querySvcBill = new QueryService<Bill>(serviceContext);
                        Customer customer = querySvc.ExecuteIdsQuery("SELECT * FROM Customer where id = '" + projectId + "'").FirstOrDefault();
                        System.Collections.ObjectModel.ReadOnlyCollection<Invoice> invoiceList = querySvcInvoice.ExecuteIdsQuery("select * from Invoice where CustomerRef = '" + projectId + "'");
                        System.Collections.ObjectModel.ReadOnlyCollection<Bill> billList = querySvcBill.ExecuteIdsQuery("select * from Bill");
                        AccountBasedExpenseLineDetail abeld = new AccountBasedExpenseLineDetail();


                    foreach (var bill in billList)
                    {

                        if (bill.Line[0].DetailType.ToString() == "AccountBasedExpenseLineDetail")
                        {
                            abeld = (AccountBasedExpenseLineDetail) bill.Line[0].AnyIntuitObject;
                            // If customerRef exist in the field it's a project related
                            if (abeld.CustomerRef != null && abeld.CustomerRef.Value == projectId)
                            {
                                listBill.Add(bill);
                            }
                            
                        }
 
                    }
                    vm.ListContrat = allContract;
                    vm.Budget = dataBudget;
                    vm.ProjectInformation = dashBoardData;
                    vm.InvoiceList = invoiceList;
                    vm.ProjectBill = listBill;
                    vm.Project = customer;
                    vm.ContratInfo = listContrat;
                    vm.Message = "QBO API call Successful!!";
                    return View("DashBoard", vm);
                }
                catch (Exception ex)
                {
                    vm.Message = "QBO API call Failed!" + " Error message: " + ex.Message;
                    // ToDo Créer une vue d'erreur d'appel API
                    return View("DashBoard", vm);
                }
            }
            else
            {
                vm.Message = "QBO API call Failed!";
                // TODO créer une vue d'erreur d'appel API
                return View("DashBoard", vm);
            }
        }
        [HttpGet]
        public ActionResult ContractDashboard(int id)
        {
            SingleProjectData vm = new SingleProjectData();
            
            if (Session["realmId"] != null)
            {
                try
                {
                    var dashBoardData = (from c in _db.Contrats
                                     where c.Project_Id == id
                                     select new ProjectInformation
                                     {
                                         Contract_Id = c.Contract_Id,
                                         ContractAmount = c.Amount,

MvcCodeFlowClientManual/Views/App/AddBudget.cshtml
@{
    ViewBag.Title = "AddBudget";
}
<div class="add-budget-form">
    <h2>AddBudget</h2>

    @using (Html.BeginForm("InsertBudget", "App", FormMethod.Post))
    {
        <div>
            <input type="number" step="0.01" name="amount" />
            <input type="hidden" name="project" value=@Model.Project_Id />
            <input class="add-budget-button" type="submit" name="submitButton" value="InsertBudget" />
        </div>
        <br />

        <br />
    }

</div>

MvcCodeFlowClientManual/Views/App/AddCategory.cshtml
@model MvcCodeFlowClientManual.Model.Project
@{
    ViewBag.Title = "AddCategory";
}

<h2>Category</h2>

@using (Html.BeginForm("InsertContract", "App", FormMethod.Post))
{
    <div>
        <input name="name" />
        <input type="hidden" name="project" value=@Model.Project_Id />
        <input type="submit" name="submitButton" value="API Call Project" />
    </div>
    <br />

    <br />
}

MvcCodeFlowClientManual/Views/App/AddContratBudget.cshtml
@{
    ViewBag.Title = "AddBudget";
}
<div class="add-contract-budget-form">
    <h2>Ajouter un budget au Contrat</h2>

    @using (Html.BeginForm("UpdateContratBudget", "App", FormMethod.Post))
    {
        <div>
            <label>Montant du budget</label><br/>
            <input type="number" step="0.01" name="amount" placeholder="Montant en $"/><br/><br />
            <input type="hidden" name="project" value=@Model.Project_Id />
            <input type="hidden" name="contract" value=@Model.Contract_Id />
            <input class="add-contract-budget-button" type="submit" name="submitButton" value="Confirmer" />
        </div>
        <br />

        <br />
    }

</div>

MvcCodeFlowClientManual/Views/App/AddDepense.cshtml
@{
    ViewBag.Title = "AjouterDepense";
}

<div class="form-depense">
    <h2>Ajouter une dépense</h2>

    @using (Html.BeginForm("InsertDepense", "App", FormMethod.Post))
    {
        <div>
            <label>Montant de la dépense:</label><br />
            <input type="number" step="0.01" name="amount" placeholder="Montant en $"/><br />
            <label>Choisissez une catégorie:</label><br />

            <select name="category" id="category">
                @foreach (var category in Model.CategoryList)
                {
                    <option value="@category.CategoryId">@category.Name</option>
                }
            </select><br /><br />
            <input type="hidden" name="contract" value=@Model.Contract_Id />
            <input type="hidden" name="project" value=@Model.Project_Id />
            <input class="add-depense-button" type="submit" name="submitButton" value="Ajouter Dépense" />
        </div>
        <br />

        <br />
    }

    @using (Html.BeginForm("InsertCategory", "App", FormMethod.Post))
    {
        <div>
            <h2>Ajouter une catégorie</h2>
            <input name="name" placeholder="Nom de la catégorie"/><br/><br />
            <input type="hidden" name="contract" value=@Model.Contract_Id />
            <input type="hidden" name="project" value=@Model.Project_Id />
            <input class="add-depense-button" type="submit" name="submitButton" value="Ajouter Catégorie" />
        </div>
    }
</div>

MvcCodeFlowClientManual/Views/App/ApiCallService.cshtml
@model MvcCodeFlowClientManual.Model.ProjectData
@{
    ViewBag.Title = "Project";
}

<div class="form-project">
    <h2>Choisissez votre projet:</h2>

    @using (Html.BeginForm("GetSelectedProjectId", "App", FormMethod.Post))
    {
        <div>
            <select name="project" id="project">
                @foreach (var Project in @Model.Project)
                {
                    <option value=@Project.Id>@Project.DisplayName</option>
                }
            </select>
        </div>
        <br />

        <div>
            <input class="api-call-service-button" type="submit" name="submitButton" value="Confirmer" onclick="location.href='@Url.Action("Action", "Home")?Value=' + $('#txtValue').val()" />
        </div>
        <br />

        <br />
    }
</div>

MvcCodeFlowClientManual/Views/App/BillDashBoard.cshtml
<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 bg-dark">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                    <span class="fa fa-th-large">Menu</span>
                </a>
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                    <li class="nav-item">
                        <a href="/App/ApiCallService" class="nav-link align-middle px-0">
                            <i class="fa fa-th-large"></i> <span class="ms-1 d-none d-sm-inline">Projet</span>
                        </a>
                    </li>
                    <li>
                        <a href="/App/DashBoard/@Model.Project_Id" class="nav-link px-0 align-middle">
                            <i class="fa fa-th-large"></i> <span class="ms-1 d-none d-sm-inline">DashBoard</span>
                        </a>
                    </li>
                    <li>
                        <a href="/App/BudgetUpdate/@Model.Project_Id" class="nav-link px-0 align-middle">
                            <i class="fa fa-usd"></i> <span class="ms-1 d-none d-sm-inline">Budget</span>
                        </a>
                    </li>
                    <li>
                        <a href="/App/AddContract/@Model.Project_Id" class="nav-link px-0 align-middle">
                            <i class="fa fa-plus"></i> <span class="ms-1 d-none d-sm-inline">Ajouter Contrat</span>
                        </a>
                    </li>
                    <li>
                        <a href="/App/SeeAllDepense/@Model.Project_Id" data-bs-toggle="collapse" class="nav-link px-0 align-middle ">
                            <i class="fa fa-eye"></i> <span class="ms-1 d-none d-sm-inline">Voir Dépenses</span>
                        </a>
                        <ul class="collapse nav flex-column ms-1" id="submenu2" data-bs-parent="#menu">
                            <li class="w-100">
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 1</a>
                            </li>
                            <li>
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 2</a>
                            </li>
                        </ul>
                    </li>
                </ul>
                <hr>
            </div>
        </div>
        <!-- Main page -->
        <div class="col-md-7">
            <div class="col-md-11">
                <div class="jumbotron">
                    <h2>Liste des dépenses quickbook</h2>
                </div>
            </div>
            <div class="row">

                @foreach (var bill in Model.ProjectBill)
                {
                    <div class="col-md-6">
                        <div class="jumbotron">
                            <h1>Montant @bill.Line[0].Amount $</h1>
                            <h1>Description : @bill.Line[0].Description</h1>

                            <h1>Catégorie :<br /> @bill.Line[0].AnyIntuitObject.AccountRef.name</h1>

                        </div>
                    </div>

                }
            </div>
        </div>
    </div>
</div>

MvcCodeFlowClientManual/Views/App/ContractDashboard.cshtml
    
@{ decimal profitEstimé = 0; }
<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 bg-dark">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                    <span class="fa fa-th-large">Menu</span>
                </a>
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                    <li class="nav-item">
                        <a href="/App/ApiCallService" class="nav-link align-middle px-0">
                            <i class="fa fa-th-large"></i> <span class="ms-1 d-none d-sm-inline">Projet</span>
                        </a>
                    </li>
                        <li>
                            <a href="/App/DashBoard/@Model.Project_Id" class="nav-link px-0 align-middle">
                                <i class="fa fa-th-large"></i> <span class="ms-1 d-none d-sm-inline">DashBoard</span>
                            </a>
                        </li>
                        <li>
                            <a href="/App/BudgetUpdate/@Model.Project_Id" class="nav-link px-0 align-middle">
                                <i class="fa fa-usd"></i> <span class="ms-1 d-none d-sm-inline">Budget</span>
                            </a>
                        </li>
                    <li>
                        <a href="/App/AddContract/@Model.Project_Id" class="nav-link px-0 align-middle">
                            <i class="fa fa-plus"></i> <span class="ms-1 d-none d-sm-inline">Ajouter Contrat</span>
                        </a>
                    </li>
                    <li>
                        <a href="/App/SeeAllDepense/@Model.Project_Id" data-bs-toggle="collapse" class="nav-link px-0 align-middle ">
                            <i class="fa fa-eye"></i> <span class="ms-1 d-none d-sm-inline">Voir Dépenses</span>
                        </a>
                        <ul class="collapse nav flex-column ms-1" id="submenu2" data-bs-parent="#menu">
                            <li class="w-100">
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 1</a>
                            </li>
                            <li>
                                <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 2</a>
                            </li>
                        </ul>
                    </li>
                </ul>
                <hr>
            </div>
        </div>
        <!-- Main page -->
        <div class="col-md-7">
            <div class="col-md-11">
                <div class="jumbotron">
                    <h2>Liste des Contrats</h2>
                </div>
            </div>
            <div class="row">
                    
                @foreach (var contrat in Model.ProjectInformation)
                {
                    { profitEstimé = contrat.ContractAmount - contrat.BudgetContratAmount; }
                    <div class="col-md-4">
                        <div class="jumbotron">
                            <h1>@contrat.ContratName</h1>
                            <h1>@contrat.ContractAmount $</h1>
                            <h1>Budget</h1>
                            <h1>@contrat.BudgetContratAmount $</h1>
                            <h1>Profit estimé</h1>
                            <h1>@profitEstimé $</h1>
                            @using (Html.BeginForm("AddDepense", "App", FormMethod.Post))
                            {
                                <div>
                                    <input type="hidden" name="contract" value=@contrat.Contract_Id />
                                    <input type="hidden" name="project" value=@Model.Project_Id />
                                    <input class="contract-dashboard-button" type="submit" name="submitButton" value="Ajouter Dépense" />
                                </div>
                                <br />

                                <br />
                            }
                            @using (Html.BeginForm("SeeContractDepense", "App", FormMethod.Post))
                            {
                                <div>
                                    <input type="hidden" name="contract" value=@contrat.Contract_Id />
                                    <input type="hidden" name="project" value=@Model.Project_Id />
                                    <input class="contract-dashboard-button" type="submit" name="submitButton" value="Voir Dépense" />
                                </div>
                                <br />

                                <br />
                            }
                            @using (Html.BeginForm("AddContratBudget", "App", FormMethod.Post))
                            {
                                <div>
                                    <input type="hidden" name="contract" value=@contrat.Contract_Id />
                                    <input type="hidden" name="project" value=@Model.Project_Id />
                                    <input class="contract-dashboard-button" type="submit" name="submitButton" value="Ajouter Budget" />
                                </div>
                                <br />

                                <br />
                            }
                        </div>
                            
                    </div>
                        
                }
            </div>
        </div>
    </div>
</div>      

MvcCodeFlowClientManual/Views/App/DashBoard.cshtml
@model MvcCodeFlowClientManual.Model.SingleProjectData
@{
    ViewBag.Title = "API Call Project Response";
}
@{
    decimal totalRevenu = 0;
    decimal totalDepense = 0;
    decimal Profit = 0;
    decimal totalRevenuEstime = 0;
    decimal totalDepenseEstime = 0;
    decimal ProfitEstime = 0;
}

<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 bg-dark">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                    <span class="fa fa-th-large">Menu</span>
                </a>
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                    <li class="nav-item">
                        <a href="/App/ApiCallService" class="nav-link align-middle px-0">
                            <i class="fa fa-th-large"></i> <span class="ms-1 d-none d-sm-inline">Projet</span>
                        </a>
                    </li>
                    @if (@Model.Budget == 0)
                    {
                    <li>
                        <a href="/App/Budget/@Model.Project.Id" class="nav-link px-0 align-middle">
                            <i class="fa fa-usd"></i> <span class="ms-1 d-none d-sm-inline">Budget</span>
                        </a>
                    </li>
                    } else 
                    {
                        <li>
                            <a href="/App/BudgetUpdate/@Model.Project.Id" class="nav-link px-0 align-middle">
                                <i class="fa fa-usd"></i> <span class="ms-1 d-none d-sm-inline">Budget</span>
                            </a>
                        </li>
                    }
                    
                    <li>
                        <a href="/App/AddContract/@Model.Project.Id" class="nav-link px-0 align-middle">
                            <i class="fa fa-plus"></i> <span class="ms-1 d-none d-sm-inline">Ajouter Contrat</span>
                        </a>
                    </li>
                    <li>
                        <a href="/App/ContractDashboard/@Model.Project.Id" data-bs-toggle="collapse" class="nav-link px-0 align-middle ">
                            <i class="fa fa-eye"></i> <span class="ms-1 d-none d-sm-inline">Voir Contrats</span>
                        </a>
                    </li>
                </ul>
                <hr>
            </div>
        </div>
        <!-- Main page -->
        <div class="col-md-7">
            <div class="col-md-11">
                <div class="jumbotron">
                    <h2>Projet : @Model.Project.DisplayName</h2>
                </div>
            </div>
            <!-- Information QuickBook -->
            <div class="row">
                <div class="col-md-12">
                    <h1>Information financière comptabilisée</h1><br />
                </div>
                <div class="col-md-4">
                    <div class="jumbotron">
                        @foreach (var invoice in Model.InvoiceList)
                        {
                            { totalRevenu += @invoice.Line[0].Amount; }
                        }
                        <h2>Revenu <br />@totalRevenu $</h2>
                        @using (Html.BeginForm("InvoiceDashBoard", "App", FormMethod.Post))
                        {
                            <div>
                                <input type="hidden" name="project" value=@Model.Project.Id />
                                <input class="contract-dashboard-button" type="submit" name="submitButton" value="Revenu Détaillé" />
                            </div>
                            <br />

                            <br />
                        }
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="jumbotron">
                        @foreach (var bill in Model.ProjectBill)
                        {
                            { totalDepense += @bill.Line[0].Amount; }
                        }
                        <h2>Dépense <br />@totalDepense $</h2>
                        @using (Html.BeginForm("BillDashBoard", "App", FormMethod.Post))
                        {
                            <div>
                                <input type="hidden" name="project" value=@Model.Project.Id />
                                <input class="contract-dashboard-button" type="submit" name="submitButton" value="Revenu Détaillé" />
                            </div>
                            <br />

                            <br />
                        }
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="jumbotron">
                        @{ Profit = totalRevenu - totalDepense; }
                        <h2>Profit <br />@Profit $</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <h1>Information financière estimée</h1><br />
                </div>
                <div class="col-md-4">
                    <div class="jumbotron">
                        @foreach (var amount in Model.ListContrat)
                        {
                            { totalRevenuEstime += @amount.ContractAmount; }
                        }
                        @foreach (var contrat in Model.ProjectInformation)
                        {
                            { totalDepenseEstime += @contrat.DepenseAmount; }
                        }
                        @{ ProfitEstime = totalRevenuEstime - totalDepenseEstime; }
                        <h2>Revenu <br /> estimé <br />@totalRevenuEstime $</h2>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="jumbotron">
                        <h2>Dépense <br />estimé<br /> @totalDepenseEstime $</h2>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="jumbotron">
                        <h2>Profit <br />estimé <br /> @ProfitEstime $</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-11">
                    <div class="jumbotron">
                        <h2>Buget du projet @Model.Budget $</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

MvcCodeFlowClientManual/Views/App/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>QuickBooks project manager</h1>
    <h2>Connectez-vous à votre compte QuickBook</h2>
</div>

<div class="row">
    <div class="col-md-8">
        @using (Html.BeginForm("InitiateAuth", "App", FormMethod.Post))
        {

            <div><input type="submit" name="submitButton" value="Connect to QuickBooks"/></div>
            <br/>
          
            <br/>
        }
</div>
</div>

MvcCodeFlowClientManual/Views/App/Tokens.cshtml
@{
    ViewBag.Title = "Tokens";
}

<br />

@foreach (var claim in System.Security.Claims.ClaimsPrincipal.Current.Claims)
{

    if (@claim.Type == "access_token")
    {
        <h1>Identification réussi!</h1>

        break;
    }

}

<br />

@using (Html.BeginForm("ApiCallService", "App", FormMethod.Post))
{

    <div><input class="token-page-button" type="submit" name="submitButton" value="Continuez" /></div>
    <br />

    <br />
}

MvcCodeFlowClientManual/Views/App/UpdateBudget.cshtml
@{
    ViewBag.Title = "UpdateBudget";
}
<div class="add-budget-form">
    <h1>Votre budget est de : @Model.BudgetAmount $</h1>
    <h2>Changer votre budget </h2>

    @using (Html.BeginForm("UpdateBudget", "App", FormMethod.Post))
    {
        <div>
            <label>Montant du budget</label><br/>
            <input type="number" step="0.01" name="amount" placeholder="Montant en $"/><br/><br/>
            <input type="hidden" name="project" value=@Model.Project_Id />
            <input class="add-budget-button" type="submit" name="submitButton" value="Confirmer" />
        </div>
        <br />

        <br />
    }
</div>